<?php

namespace Container5Bmwd2e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zGwis69.App\Entity\Coupon' shared service.
     *
     * @return \App\Entity\Coupon
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zGwis69": it references class "App\\Entity\\Coupon" but no such service exists.');
    }
}
