<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Bmwd2e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Bmwd2e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Bmwd2e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Bmwd2e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5Bmwd2e\App_KernelDevDebugContainer([
    'container.build_hash' => '5Bmwd2e',
    'container.build_id' => '6a0ee15a',
    'container.build_time' => 1663627140,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Bmwd2e');
